FROM --platform=linux/aarch64 fedora:latest

# Windows build deps
RUN dnf install ninja-build clang zip -y
RUN dnf install -y git make cmake gcc g++

ENV VCPKG_DEFAULT_TRIPLET=arm64-linux
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
ENV VCPKG_USE_SYSTEM_BINARIES=1

RUN git clone https://github.com/microsoft/vcpkg.git
RUN cd /vcpkg && ./bootstrap-vcpkg.sh


# Linux build deps
RUN dnf install -y dnf-plugins-core
RUN dnf builddep -y qemu

WORKDIR /

RUN git clone -b stable-8.2 https://github.com/qemu/qemu.git

COPY --chmod=777 ./build_windows_aarch64.sh /build_windows.sh

CMD ["/bin/bash", "/build_windows.sh", "aarch64-w64-mingw32-"]
