FROM debian

# Install dependencies
RUN apt-get update && apt-get install -y wget

# Download the Windows SDK installer
WORKDIR /sdk
RUN wget -O sdksetup.iso "https://go.microsoft.com/fwlink/?linkid=2300755"

RUN dpkg --add-architecture i386 && apt-get update && apt-get install -y wine32:i386
RUN apt-get install -y p7zip-full cabextract wine64

RUN 7z x sdksetup.iso -o/sdk/extracted

ENV DISPLAY=:0
RUN wine regedit "HKEY_CURRENT_USER\\Software\\Wine\\X11 Driver" /v UseDirect3D /t REG_DWORD /d 1

# Provide an entry point to copy the extracted files
CMD ["/bin/bash"]