version: 2.1

setup: true

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux-x86_64
      - build-linux-aarch64
      - build-macos-x86_64
      - build-macos-aarch64
      - build-windows-x86_64
      - build-windows-aarch64

import:
  - jobs/linux.yml
  - jobs/macos.yml
  - jobs/windows.yml