jobs:
    build-linux-aarch64:
        machine:
            image: ubuntu-2404:2024.08.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: docker build -t build-linux-aarch64 -f ./Dockerfile_linux_aarch64 .
            - run: docker run -v /build:/mnt/build build-linux-aarch64
            - run: sudo chown $USER /build/qemu\(aarch64\)-aarch64-unknown-linux-gnu
            - persist_to_workspace:
                paths:
                    - qemu(aarch64)-aarch64-unknown-linux-gnu
                root: /build
    build-linux-x86_64:
        machine:
            image: ubuntu-2404:2024.08.1
        steps:
            - checkout
            - run: docker build -t build-linux-x86-64 -f ./Dockerfile_linux_x86_64 .
            - run: docker run -v /build:/mnt/build build-linux-x86-64
            - run: ls ./build && sudo chown $USER ./build/qemu\(x86_64\)-x86_64-unknown-linux-gnu
            - persist_to_workspace:
                paths:
                    - qemu(x86_64)-x86_64-unknown-linux-gnu
                root: /build
    build-macos:
        macos:
            xcode: 14.2.0
        resource_class: macos.m1.medium.gen1
        steps:
            - checkout
            - run: brew install ninja glib
            - run: ./build_macos.sh
            - run: mv qemu/build/qemu-system-x86_64 qemu/build/qemu-universal-apple-darwin
            - persist_to_workspace:
                paths:
                    - qemu-universal-apple-darwin
                root: qemu/build
    build-windows-aarch64:
        machine:
            image: ubuntu-2404:2024.08.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: docker build --platform=linux/arm64 -t build-windows-aarch64 -f ./Dockerfile_windows_aarch64 .
            - run: docker run --platform=linux/arm64 -v /build:/mnt/build build-windows-aarch64
            - persist_to_workspace:
                paths:
                    - qemu(aarch64)-windows-aarch64-pc-windows-gnu.exe
                root: /build
    build-windows-x86_64:
        machine:
            image: ubuntu-2404:2024.08.1
        steps:
            - checkout
            - run: docker build -t build-windows-x86-64 -f ./Dockerfile_windows_x86_64 .
            - run: docker run -v /build:/mnt/build build-windows-x86-64
            - persist_to_workspace:
                paths:
                    - qemu(x86_64)-windows-x86_64-pc-windows-gnu.exe
                root: /build
    publish-github-release:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                at: ./workspace
            - run:
                command: |
                    VERSION=8.2
                    echo "${GITHUB_TOKEN}"
                    ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" ./workspace/
                name: Release binaries
version: 2.1
workflows:
    build-crossplatform:
        jobs:
            - build-linux-aarch64
            - build-linux-x86_64
            - build-macos
            - build-windows-x86_64
            - publish-github-release:
                context:
                    - Shared Github
                requires:
                    - build-linux-aarch64
                    - build-linux-x86_64
                    - build-macos
                    - build-windows-x86_64

