jobs:
    build-linux-aarch64:
        machine:
            image: ubuntu-2204:2023.07.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-aarch64 -f ./Dockerfile_linux_aarch64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-aarch64
    build-linux-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-x86-64 -f ./Dockerfile_linux_x86_64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-x86-64
    build-macos:
        macos:
            xcode: 12.3.0
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: brew install ninja
            - run: ./build_macos.sh
    build-windows-aarch64:
        machine:
            image: ubuntu-2204:2024.05.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-windows-aarch64 -f ./Dockerfile_windows_aarch64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-aarch64
    build-windows-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-windows-x86-64 -f ./Dockerfile_windows_x86_64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-x86-64
version: 2.1
workflows:
    build-crossplatform:
        jobs:
            - build-linux-aarch64
            - build-linux-x86_64
            - build-macos
            - build-windows-aarch64
            - build-windows-x86_64

