jobs:
    build-linux-aarch64:
        machine:
            image: ubuntu-2204:2023.07.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-aarch64 -f ./Dockerfile_linux_aarch64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-aarch64
            - store_artifacts:
                destination: qemu-aarch64-unknown-linux-gnu
                path: qemu/build/qemu-system-x86_64
    build-linux-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-x86-64 -f ./Dockerfile_linux_x86_64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-x86-64
            - store_artifacts:
                destination: qemu-x86_64-unknown-linux-gnu
                path: qemu/build/qemu-system-x86_64
    build-macos:
        macos:
            xcode: 14.2.0
        resource_class: macos.m1.medium.gen1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: brew install ninja glib
            - run: ./build_macos.sh
            - store_artifacts:
                destination: qemu-universal-apple-darwin
                path: qemu/build/qemu-system-x86_64
    build-windows-aarch64:
        machine:
            image: ubuntu-2204:2024.05.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-windows-aarch64 -f ./Dockerfile_windows_aarch64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-aarch64
            - store_artifacts:
                destination: qemu-windows-aarch64-pc-windows-gnu.exe
                path: qemu/build/qemu-system-x86_64
    build-windows-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-windows-x86-64 -f ./Dockerfile_windows_x86_64 .
            - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-x86-64
            - store_artifacts:
                destination: qemu-windows-aarch64-pc-windows-gnu.exe
                path: qemu/build/qemu-system-x86_64
version: 2.1
workflows:
    build-crossplatform:
        jobs:
            - build-linux-aarch64
            - build-linux-x86_64
            - build-macos
            - build-windows-aarch64
            - build-windows-x86_64

