machine:
  image: ubuntu-2204:2023.07.1
  resource_class: arm.medium
steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init

  # Build Docker image for x86_64
  - run: docker build -t build-linux-aarch64 -f ./Dockerfile_linux_aarch64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-aarch64