machine:
  image: ubuntu-2204:2024.05.1
  resource_class: arm.medium
steps:
  - checkout

  # Build Docker image for aarch64
  - run: docker build -t build-windows-aarch64 -f ./Dockerfile_windows_aarch64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-aarch64