macos:
  xcode: 14.2.0
resource_class: macos.m1.medium.gen1
steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init

  # Install dependencies
  - run: brew install ninja glib

  - run: ./build_macos.sh

  - run: mv qemu/build/qemu-system-x86_64 qemu/build/qemu-universal-apple-darwin

  - persist_to_workspace:
      root: qemu/build
      destination: qemu-universal-apple-darwin