macos:
  xcode: 14.2.0
resource_class: macos.m1.medium.gen1
steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init

  # Install ninja
  - run: brew install ninja
  - run: ./build_macos.sh