machine:
  image: ubuntu-2204:2024.05.1
steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init
  
  # Build Docker image for x86_x64
  - run: docker build -t build-windows-x86-64 -f ./Dockerfile_windows_x86_64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./qemu):/mnt/src build-windows-x86-64

  - store_artifacts:
      path: qemu/build/qemu-system-x86_64.exe
      destination: qemu-windows-aarch64-pc-windows-gnu.exe