machine:
  image: ubuntu-2204:2023.07.1
  resource_class: arm.medium
steps:
  - checkout

  # Build Docker image for x86_64
  - run: docker build -t build-linux-aarch64 -f ./Dockerfile_linux_aarch64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./build):/mnt/build build-linux-aarch64

  - run: sudo chown $USER /build/qemu\(aarch64\)-aarch64-unknown-linux-gnu

  - persist_to_workspace:
      root: /build
      paths:
        - qemu(aarch64)-aarch64-unknown-linux-gnu