machine:
  image: ubuntu-2204:2023.07.1

steps:
  - checkout

  # Build Docker image for x86_64
  - run: docker build -t build-linux-x86-64 -f ./Dockerfile_linux_x86_64 .

  # Run Docker container with volume mount
  - run: docker run -v ./qemu:/mnt/src build-linux-x86-64