machine:
  image: ubuntu-2204:2024.05.1

steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init

  # Build Docker image for x86_64
  - run: docker build -t build-linux-x86-64 -f ./Dockerfile_linux_x86_64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./qemu):/mnt/src build-linux-x86-64

  - run: sudo chown $USER qemu/build/qemu-system-x86_64

  - run: sudo mv qemu/build/qemu-system-x86_64 qemu/build/qemu-x86_64-unknown-linux-gnu

  - persist_to_workspace:
      root: qemu/build
      paths:
        - qemu-x86_64-unknown-linux-gnu