macos:
  xcode: 14.2.0
resource_class: macos.m1.medium.gen1
steps:
  - checkout
  - run: git submodule sync
  - run: git submodule update --init

  # Install dependencies
  - run: brew install ninja glib

  - run: ./build_macos.sh

  - store_artifacts:
      path: build/qemu-universal-apple-darwin
      destination: qemu-universal-apple-darwin