machine:
  image: ubuntu-2404:2024.08.1
steps:
  - checkout
  
  # Build Docker image for x86_x64
  - run: docker build -t build-windows-x86-64 -f ./Dockerfile_windows_x86_64 .

  # Run Docker container with volume mount
  - run: docker run -v $(realpath ./build):/mnt/build build-windows-x86-64
  - persist_to_workspace:
      root: /build
      paths:
        - qemu(x86_64)-windows-x86_64-pc-windows-gnu.exe