docker:
  - image: cibuilds/github:0.10
steps:
  - attach_workspace:
      at: ./workspace
  - run:
      name: "Release binaries"
      command: |
        VERSION=9.0.1
        echo "${GITHUB_TOKEN}"