docker:
  - image: cibuilds/github:0.10
steps:
  - attach_workspace:
      at: ./artifacts
  - run:
      name: "Publish Release on GitHub"
      command: |
        VERSION=9.0.1
        ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
