version: 2.1

jobs:
  build-linux-x86_64:
    executor: linux-x86_64
    steps:
      - checkout
      - run: echo "Building on Linux x86_64"
      # Add your build steps here

  build-linux-aarch64:
    executor: linux-aarch64
    steps:
      - checkout
      - run: echo "Building on Linux aarch64"
      # Add your build steps here