on: [push]

name: 'Build Cross Platform x86_64'


permissions:
  contents: write

jobs:
  upload-release:

    runs-on: ubuntu-latest
    needs: [
      build-linux,
      build-windows,
      build-macos,
    ]

    steps:
    - uses: actions/checkout@v2
    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 9.0.1
        release_name: Release 9.0.1
        draft: false
        prerelease: false   
    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: uploads
        path: ${{ github.workspace }}/uploads
    - name: list-artifacts
      run: ls ${{ github.workspace }} && pwd && ls ${{ github.workspace }}/uploads && stat /home/runner/work/qemu-builder/qemu-builder/uploads/qemu-x86_64-pc-windows-gnu.exe
    - name: upload windows x86-64
      id: upload-windows-x86-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/uploads/qemu-x86_64-pc-windows-gnu.exe
        asset_name: qemu-x86_64-pc-windows-gnu.exe
        asset_content_type: application/octet-stream 
    - name: upload linux x86-64
      id: upload-linux-x86-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/uploads/qemu-x86_64-unknown-linux-gnu
        asset_name: qemu-x86_64-unknown-linux-gnu
        asset_content_type: application/octet-stream
    - name: upload macos x86-64
      id: upload-macos-x86-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/uploads/qemu-x86_64-apple-darwin
        asset_name: qemu-x86_64-apple-darwin
        asset_content_type: application/octet-stream
    - name: upload macos aarch64
      id: upload-macos-aarch64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/uploads/qemu-aarch64-apple-darwin
        asset_name: qemu-aarch64-apple-darwin
        asset_content_type: application/octet-stream
  build-linux:
    uses: ./.github/workflows/build-linux.yml
  build-windows:
    uses: ./.github/workflows/build-windows.yml
  build-macos:
    uses: ./.github/workflows/build-macos.yml